Pl 15
proostack/pl-frontend pull request #24
Opened 2023-05-18 11:01 UTC by Ushie01

feat: Service Apartment on mobile view[PL-15]

2023-05-19 09:56 UTC, jbrainz requested changes

2023-05-19 09:56 UTC, jbrainz commented on src/client/components/LandingPage/components/ServiceApartment/ServiceApartmentContainer/components/StarRating.tsx
> +};
There's a generic icon from moon design.
And this is a bad way of writing a rating component

2023-05-23 10:58 UTC, jbrainz requested changes

2023-05-23 10:58 UTC, jbrainz commented on src/client/components/LandingPage/components/ServiceApartment/ServiceApartmentContainer/components/StarRating.tsx
> +
I believe you can still do better here, total star is always 5. so by default you can have an unfilled star(5 outlined star). then have a props called rating, the props is what determines the amount of filled stars.

2023-05-23 17:14 UTC, Ushie01 commented on src/client/components/LandingPage/components/ServiceApartment/ServiceApartmentContainer/components/StarRating.tsx
> +
okay boss let me work on it

2023-05-23 21:13 UTC, merged